import type { AppLocale } from "@/lib/app-locale";

export const CONFIRMATION_COPY = {
  id: {
    fillBookerData: "Lengkapi data pemesan",
    back: "Kembali",
    bookingConfirm: "Konfirmasi Pemesanan",
    selfBooker: "Pemesan adalah saya sendiri",
    selfBookerHint: "Gunakan data akun login untuk nama, email, dan nomor telepon.",
    loadingAccount: "Memuat data akun...",
    accountDataFromProfile: "Data pemesan diambil dari profil akun Anda.",
    name: "Nama",
    email: "Email",
    phone: "Telepon",
    bookerName: "Nama pemesan",
    bookerEmail: "Email pemesan",
    bookerPhone: "Nomor telepon",
    inputFullName: "Masukkan nama lengkap",
    paymentMethod: "Metode pembayaran",
    manualTransfer: "Transfer Manual",
    paymentGateway: "Gateway Pembayaran",
    breakfastOption: "Opsi Sarapan",
    addBreakfast: "Tambahkan sarapan",
    breakfastPaxCount: "Jumlah pax sarapan",
    processing: "Memproses...",
    confirmBooking: "Konfirmasi Pemesanan",
    summary: "Ringkasan",
    priceDetails: "Rincian harga",
    loadingPriceDetails: "Memuat rincian harga...",
    roomSubtotal: "Subtotal kamar",
    breakfast: "Sarapan",
    appServiceFee: "Biaya layanan aplikasi (2%)",
    tax: "Pajak (11%)",
    total: "Total",
    recheckConfirm: "Konfirmasi Ulang",
    isBookingDataCorrect: "Apakah data pemesanan sudah benar?",
    recheckHint: "Pastikan tanggal, jumlah tamu, dan metode pembayaran sudah sesuai.",
    duration: "Durasi",
    payMethod: "Metode bayar",
    recheck: "Periksa lagi",
    yesContinue: "Ya, lanjutkan",
    guests: "tamu",
    nights: "malam",
    pleaseFillManual: "Silakan isi data pemesan secara manual.",
    accountUnavailable: "Data akun tidak tersedia.",
    accountUnavailableManual: "Data akun tidak tersedia. Silakan isi manual.",
    loginForFinalPrice: "Silakan login untuk melihat rincian harga final.",
    failedLoadPrice: "Gagal memuat rincian harga.",
    failedCreateBooking: "Gagal membuat pemesanan.",
    checkIn: "Check-in",
    checkOut: "Check-out",
  },
  en: {
    fillBookerData: "Complete booker details",
    back: "Back",
    bookingConfirm: "Booking Confirmation",
    selfBooker: "I am the booker",
    selfBookerHint: "Use your logged-in account data for name, email, and phone.",
    loadingAccount: "Loading account data...",
    accountDataFromProfile: "Booker data is taken from your account profile.",
    name: "Name",
    email: "Email",
    phone: "Phone",
    bookerName: "Booker name",
    bookerEmail: "Booker email",
    bookerPhone: "Phone number",
    inputFullName: "Enter full name",
    paymentMethod: "Payment method",
    manualTransfer: "Manual transfer",
    paymentGateway: "Payment gateway",
    breakfastOption: "Breakfast option",
    addBreakfast: "Add breakfast",
    breakfastPaxCount: "Breakfast pax count",
    processing: "Processing...",
    confirmBooking: "Confirm booking",
    summary: "Summary",
    priceDetails: "Price details",
    loadingPriceDetails: "Loading price details...",
    roomSubtotal: "Room subtotal",
    breakfast: "Breakfast",
    appServiceFee: "App service fee (2%)",
    tax: "Tax (11%)",
    total: "Total",
    recheckConfirm: "Final confirmation",
    isBookingDataCorrect: "Is your booking data correct?",
    recheckHint: "Please ensure date, guest count, and payment method are correct.",
    duration: "Duration",
    payMethod: "Payment method",
    recheck: "Review again",
    yesContinue: "Yes, continue",
    guests: "guests",
    nights: "nights",
    pleaseFillManual: "Please fill booker details manually.",
    accountUnavailable: "Account data is unavailable.",
    accountUnavailableManual: "Account data is unavailable. Please fill manually.",
    loginForFinalPrice: "Please sign in to view final pricing details.",
    failedLoadPrice: "Failed to load pricing details.",
    failedCreateBooking: "Failed to create booking.",
    checkIn: "Check-in",
    checkOut: "Check-out",
  },
} as const satisfies Record<AppLocale, Record<string, string>>;

export type ConfirmationCopy = Record<keyof (typeof CONFIRMATION_COPY)["id"], string>;
