export const LISTING_COPY_ID = {
  failedLoadDetail: "Gagal memuat detail properti.",
  failedLoadCalendar: "Gagal memuat kalender.",
  failedLoadDate: "Tanggal tersebut tidak tersedia penuh.",
  roomSelectionRequired: "Pilih kamar terlebih dahulu.",
  dateSelectionRequired: "Pilih tanggal check-in dan check-out untuk melanjutkan pemesanan.",
  capacityExceededPrefix: "Jumlah tamu melebihi kapasitas kamar",
  rangeUnavailable: "Rentang tanggal yang dipilih tidak tersedia penuh. Pilih tanggal lain.",
  bookingReady: "Data pemesanan sudah valid. Klik tombol untuk melanjutkan ke konfirmasi.",
  bookingPriceFrom: "Harga mulai",
  chooseRoom: "Pilih kamar",
  chooseStayDate: "Pilih tanggal menginap",
  hideCalendar: "Sembunyikan kalender",
  showCalendar: "Buka kalender",
  checkIn: "Check-in",
  checkOut: "Check-out",
  nightsSelectedSuffix: "malam dipilih.",
  loadingCalendar: "Memuat kalender...",
  pricePerNightIDR: "Harga per malam (IDR)",
  available: "Tersedia",
  selected: "Dipilih",
  unavailable: "Tidak tersedia",
  full: "Penuh",
  guestsCount: "Jumlah tamu",
  guestUnit: "tamu",
  adults: "Dewasa",
  children: "Anak-anak",
  age13Plus: "Usia 13+",
  age0to12: "Usia 0-12",
  maxCapacityPrefix: "Kapasitas maksimal",
  breakfastOption: "Opsi sarapan",
  noBreakfastOption: "Properti ini tidak menyediakan opsi sarapan.",
  withoutBreakfast: "Tanpa sarapan",
  withBreakfast: "Dengan sarapan",
  perPaxPerNight: "per pax per malam",
  breakfastPax: "Pax sarapan",
  maxPaxPrefix: "Maksimal",
  bookNow: "Pesan sekarang",
  completeBookingData: "Lengkapi data pemesanan",
  loadingDetail: "Memuat detail properti...",
  featuredProperty: "Properti pilihan",
  indonesia: "Indonesia",
  photoOf: "Foto",
  from: "dari",
  previous: "Sebelumnya",
  next: "Selanjutnya",
  roomsAvailableSuffix: "tipe kamar tersedia.",
  noDescription: "Tenant belum menambahkan deskripsi properti.",
  propertyAmenities: "Fasilitas properti",
  amenitiesSuffix: "fasilitas",
  showAllAmenities: "Lihat semua fasilitas",
  noAmenities: "Tenant belum menambahkan fasilitas untuk properti ini.",
  roomOptions: "Pilihan room",
  capacity: "Kapasitas",
  unit: "unit",
  selectedLabel: "Dipilih",
  selectRoom: "Pilih room",
  propertyLocation: "Lokasi Properti",
  locationDesc: "Titik properti ditampilkan melalui peta interaktif untuk memudahkan orientasi area.",
  whatPlaceOffers: "Yang tersedia di properti ini",
  closeAmenitiesModalAria: "Tutup popup fasilitas",
  perNight: "per malam",
  finalPriceHint: "Harga final akan menyesuaikan tanggal dan opsi tamu.",
} as const;
