export const LISTING_COPY_EN = {
  failedLoadDetail: "Failed to load property detail.",
  failedLoadCalendar: "Failed to load calendar.",
  failedLoadDate: "The selected date range is not fully available.",
  roomSelectionRequired: "Please select a room first.",
  dateSelectionRequired: "Please select check-in and check-out dates to continue.",
  capacityExceededPrefix: "Guest count exceeds room capacity",
  rangeUnavailable: "The selected date range is not fully available. Please choose another date.",
  bookingReady: "Booking data is valid. Continue to confirmation.",
  bookingPriceFrom: "Starting from",
  chooseRoom: "Choose room",
  chooseStayDate: "Choose stay dates",
  hideCalendar: "Hide calendar",
  showCalendar: "Open calendar",
  checkIn: "Check-in",
  checkOut: "Check-out",
  nightsSelectedSuffix: "nights selected.",
  loadingCalendar: "Loading calendar...",
  pricePerNightIDR: "Price per night (IDR)",
  available: "Available",
  selected: "Selected",
  unavailable: "Unavailable",
  full: "Sold out",
  guestsCount: "Guest count",
  guestUnit: "guests",
  adults: "Adults",
  children: "Children",
  age13Plus: "Age 13+",
  age0to12: "Age 0-12",
  maxCapacityPrefix: "Maximum capacity",
  breakfastOption: "Breakfast option",
  noBreakfastOption: "This property does not provide breakfast.",
  withoutBreakfast: "Without breakfast",
  withBreakfast: "With breakfast",
  perPaxPerNight: "per pax per night",
  breakfastPax: "Breakfast pax",
  maxPaxPrefix: "Maximum",
  bookNow: "Book now",
  completeBookingData: "Complete booking details",
  loadingDetail: "Loading property detail...",
  featuredProperty: "Featured property",
  indonesia: "Indonesia",
  photoOf: "Photo",
  from: "of",
  previous: "Previous",
  next: "Next",
  roomsAvailableSuffix: "room types available.",
  noDescription: "Tenant has not added a property description yet.",
  propertyAmenities: "Property amenities",
  amenitiesSuffix: "amenities",
  showAllAmenities: "Show all amenities",
  noAmenities: "Tenant has not added amenities for this property yet.",
  roomOptions: "Room options",
  capacity: "Capacity",
  unit: "units",
  selectedLabel: "Selected",
  selectRoom: "Select room",
  propertyLocation: "Property location",
  locationDesc: "Property point is shown on an interactive map to help area orientation.",
  whatPlaceOffers: "What this place offers",
  closeAmenitiesModalAria: "Close amenities popup",
  perNight: "per night",
  finalPriceHint: "Final price may vary based on dates and guest options.",
} as const;
