import type { ReviewCopyMap } from "./my-review-types";

export const REVIEW_COPY: ReviewCopyMap = {
  id: {
    loginAgain: "Silakan login kembali.",
    failedLoad: "Gagal memuat data review.",
    failedReview: "Gagal mengirim review.",
    reviewSuccess: "Review berhasil dikirim.",
    ratingRange: "Rating review harus antara 1 sampai 5.",
    reviewRequired: "Komentar review wajib diisi.",
    pageEyebrow: "Pusat Review",
    pageTitle: "Kelola review transaksi Anda",
    pageSubtitle: "Pisahkan proses review dari daftar transaksi agar alur lebih fokus dan rapi.",
    backTransactions: "Kembali ke Transaksi",
    backHome: "Kembali ke Beranda",
    refresh: "Muat Ulang",
    refreshing: "Memuat...",
    pendingTitle: "Perlu direview",
    pendingEmpty: "Tidak ada transaksi selesai yang menunggu review.",
    historyTitle: "Riwayat review",
    historyEmpty: "Belum ada review yang dikirim.",
    orderNoLabel: "Nomor pesanan",
    searchOrderPlaceholder: "Cari nomor pesanan",
    applySearch: "Cari",
    resetSearch: "Atur Ulang",
    pendingCount: "Menunggu review",
    reviewedCount: "Sudah direview",
    reviewSentAt: "Dikirim",
    tenantReply: "Balasan Tenant",
    tenantRepliedAt: "Dibalas pada",
    bookedAt: "Dipesan",
    stayPeriod: "Periode menginap",
    duration: "Durasi",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guestsRooms: "Tamu / Kamar",
    paymentMethod: "Metode Bayar",
    total: "Total",
    fallbackRoomName: "Kamar",
    writeReview: "Tulis Ulasan",
    reviewPlaceholder: "Bagikan pengalaman menginap Anda...",
    submitReview: "Kirim Ulasan",
    submittingReview: "Mengirim...",
    highlightedBooking: "Anda membuka halaman ini dari transaksi yang dipilih.",
    highlightedNotFound: "Transaksi yang dipilih tidak ditemukan atau sudah direview. Coba muat ulang data.",
    sortByLabel: "Urutkan berdasarkan",
    sortOrderLabel: "Arah urutan",
    sortByCreatedAt: "Tanggal dibuat",
    sortByCheckIn: "Tanggal check-in",
    sortByTotalAmount: "Total transaksi",
    sortByOrderNo: "Nomor pesanan",
    sortOrderAsc: "Menaik",
    sortOrderDesc: "Menurun",
    pageInfo: "Halaman",
    prevPage: "Sebelumnya",
    nextPage: "Berikutnya",
    ratingOptions: [
      { value: "5", label: "5 - Sangat baik" },
      { value: "4", label: "4 - Baik" },
      { value: "3", label: "3 - Cukup" },
      { value: "2", label: "2 - Kurang" },
      { value: "1", label: "1 - Buruk" },
    ],
  },
  en: {
    loginAgain: "Please sign in again.",
    failedLoad: "Failed to load review data.",
    failedReview: "Failed to submit review.",
    reviewSuccess: "Review submitted successfully.",
    ratingRange: "Review rating must be between 1 and 5.",
    reviewRequired: "Review comment is required.",
    pageEyebrow: "Review Center",
    pageTitle: "Manage your transaction reviews",
    pageSubtitle: "Keep the review workflow separate from transactions so the flow stays cleaner.",
    backTransactions: "Back to Transactions",
    backHome: "Back to Home",
    refresh: "Refresh",
    refreshing: "Refreshing...",
    pendingTitle: "Need review",
    pendingEmpty: "No completed transactions are waiting for review.",
    historyTitle: "Review history",
    historyEmpty: "No review submitted yet.",
    orderNoLabel: "Order number",
    searchOrderPlaceholder: "Search order number",
    applySearch: "Search",
    resetSearch: "Reset",
    pendingCount: "Pending review",
    reviewedCount: "Reviewed",
    reviewSentAt: "Submitted",
    tenantReply: "Tenant Reply",
    tenantRepliedAt: "Replied at",
    bookedAt: "Booked",
    stayPeriod: "Stay period",
    duration: "Duration",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guestsRooms: "Guests / Rooms",
    paymentMethod: "Payment method",
    total: "Total",
    fallbackRoomName: "Room",
    writeReview: "Write Review",
    reviewPlaceholder: "Share your stay experience...",
    submitReview: "Submit Review",
    submittingReview: "Submitting...",
    highlightedBooking: "You opened this page from a selected transaction.",
    highlightedNotFound: "Selected transaction was not found or already reviewed. Try refreshing data.",
    sortByLabel: "Sort by",
    sortOrderLabel: "Sort direction",
    sortByCreatedAt: "Created date",
    sortByCheckIn: "Check-in date",
    sortByTotalAmount: "Transaction total",
    sortByOrderNo: "Order number",
    sortOrderAsc: "Ascending",
    sortOrderDesc: "Descending",
    pageInfo: "Page",
    prevPage: "Previous",
    nextPage: "Next",
    ratingOptions: [
      { value: "5", label: "5 - Excellent" },
      { value: "4", label: "4 - Good" },
      { value: "3", label: "3 - Fair" },
      { value: "2", label: "2 - Poor" },
      { value: "1", label: "1 - Bad" },
    ],
  },
};
