import type { AppLocale } from "@/lib/app-locale";

export const LOGIN_COPY = {
  id: {
    tenantTitle: "Masuk sebagai tenant",
    userTitle: "Masuk",
    tenantSubtitle: "Masuk untuk mengelola properti anda bersama kami.",
    userSubtitle: "Lanjutkan pencarian dan pemesanan properti Anda.",
    submit: "Masuk",
    invalidEmail: "Format email tidak valid.",
    passwordMin: "Password minimal 8 karakter.",
    notTenant: "Akun ini bukan akun tenant. Gunakan halaman masuk pengguna.",
    isTenant: "Akun ini tenant. Gunakan halaman masuk Tenant.",
    tokenMissing: "Token tidak ditemukan.",
    loginFailed: "Gagal masuk.",
    verifyFirst: "Silakan verifikasi email terlebih dahulu.",
    validEmailFirst: "Masukkan email yang valid terlebih dahulu.",
    resendFailed: "Gagal mengirim ulang.",
    userMode: "Mode Pengguna",
    tenantMode: "Mode Tenant",
    welcome: "Selamat datang",
    email: "Email",
    password: "Password",
    forgotPassword: "Lupa kata sandi?",
    passwordPlaceholder: "Masukkan password Anda",
    processing: "Memproses...",
    sending: "Mengirim...",
    resendVerification: "Kirim ulang email verifikasi",
    continueWith: "atau lanjutkan dengan",
    noTenantAccount: "Belum memiliki akun tenant?",
    registerTenant: "Daftar Tenant",
    loginAsUser: "Masuk sebagai pengguna?",
    userLogin: "Masuk Pengguna",
    noAccount: "Belum memiliki akun?",
    registerAccount: "Daftar Akun",
    wantTenant: "Ingin mendaftar sebagai tenant?",
    terms:
      "Dengan masuk,anda menyetujui persyaratan layanan dan kebijakan privasi kami.",
  },
  en: {
    tenantTitle: "Sign in as tenant",
    userTitle: "Sign in",
    tenantSubtitle: "Sign in to manage your property with us.",
    userSubtitle: "Continue searching and booking your properties.",
    submit: "Sign in",
    invalidEmail: "Invalid email format.",
    passwordMin: "Password must be at least 8 characters.",
    notTenant: "This account is not a tenant account. Use user sign-in page.",
    isTenant: "This account is tenant. Use tenant sign-in page.",
    tokenMissing: "Token not found.",
    loginFailed: "Sign-in failed.",
    verifyFirst: "Please verify your email first.",
    validEmailFirst: "Please enter a valid email first.",
    resendFailed: "Failed to resend.",
    userMode: "User Mode",
    tenantMode: "Tenant Mode",
    welcome: "Welcome",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    passwordPlaceholder: "Enter your password",
    processing: "Processing...",
    sending: "Sending...",
    resendVerification: "Resend verification email",
    continueWith: "or continue with",
    noTenantAccount: "Don't have a tenant account?",
    registerTenant: "Register Tenant",
    loginAsUser: "Sign in as user?",
    userLogin: "User Sign-in",
    noAccount: "Don't have an account?",
    registerAccount: "Register Account",
    wantTenant: "Want to register as tenant?",
    terms: "By signing in, you agree to our Terms and Privacy Policy.",
  },
} as const;

export const getLoginCopy = (locale: AppLocale) => LOGIN_COPY[locale];

export type LoginCopy = (typeof LOGIN_COPY)[keyof typeof LOGIN_COPY];
