import type { AppLocale } from "@/lib/app-locale";

export const REGISTER_COPY = {
  id: {
    popupMessage: "Tautan verifikasi telah dikirim.",
    tenantTitle: "Daftar Tenant",
    userTitle: "Daftar Akun",
    tenantSubtitle: "Buat akun tenant untuk mulai mengelola properti Anda.",
    userSubtitle: "Buat akun untuk mulai mencari dan memesan properti.",
    submit: "Daftar",
    invalidEmail: "Format email tidak valid.",
    registerFailed: "Registrasi gagal.",
    login: "Masuk",
    checkInbox: "Periksa inbox atau folder spam untuk melanjutkan verifikasi.",
    close: "Tutup",
    createTenantAccount: "Buat akun tenant Anda",
    createUserAccount: "Buat akun BookIn Anda",
    email: "Email",
    processing: "Memproses...",
    continueWith: "atau lanjutkan dengan",
    alreadyTenant: "Sudah terdaftar sebagai tenant?",
    alreadyHaveAccount: "Sudah memiliki akun?",
    wantTenant: "Ingin mendaftar sebagai tenant?",
    wantUser: "Ingin mendaftar sebagai pengguna?",
    registerTenant: "Daftar Tenant",
    registerAccount: "Daftar Akun",
    terms:
      "Dengan mendaftar, Anda menyetujui Kebijakan Privasi dan Syarat Penggunaan BookIn.",
  },
  en: {
    popupMessage: "Verification link has been sent.",
    tenantTitle: "Register Tenant",
    userTitle: "Register Account",
    tenantSubtitle: "Create a tenant account to start managing properties.",
    userSubtitle: "Create an account to start searching and booking properties.",
    submit: "Register",
    invalidEmail: "Invalid email format.",
    registerFailed: "Registration failed.",
    login: "Sign in",
    checkInbox: "Check your inbox or spam folder to continue verification.",
    close: "Close",
    createTenantAccount: "Create your tenant account",
    createUserAccount: "Create your BookIn account",
    email: "Email",
    processing: "Processing...",
    continueWith: "or continue with",
    alreadyTenant: "Already registered as tenant?",
    alreadyHaveAccount: "Already have an account?",
    wantTenant: "Want to register as tenant?",
    wantUser: "Want to register as user?",
    registerTenant: "Register Tenant",
    registerAccount: "Register Account",
    terms: "By registering, you agree to BookIn Terms and Privacy Policy.",
  },
} as const;

export const getRegisterCopy = (locale: AppLocale) => REGISTER_COPY[locale];
