import type { TransactionCopyMap } from "./my-transaction-types";

export const TRANSACTION_COPY: TransactionCopyMap = {
  id: {
    loginAgain: "Silakan login kembali.",
    failedLoad: "Gagal memuat transaksi.",
    failedReview: "Gagal mengirim review.",
    reviewSuccess: "Review berhasil dikirim.",
    ratingRange: "Rating review harus antara 1 sampai 5.",
    reviewRequired: "Komentar review wajib diisi.",
    historyEyebrow: "Riwayat Transaksi",
    historyTitle: "Daftar transaksi pemesanan Anda",
    historySubtitle: "Cari berdasarkan nomor pesanan atau rentang tanggal pembuatan transaksi.",
    backHome: "Kembali ke Beranda",
    myReviews: "Review Saya",
    refresh: "Muat Ulang",
    refreshing: "Memuat ulang...",
    searchOrderPlaceholder: "Cari nomor pesanan",
    applySearch: "Cari",
    resetSearch: "Atur Ulang",
    emptyState: "Belum ada transaksi.",
    fallbackRoomName: "Kamar",
    bookedAt: "Dipesan",
    stayPeriod: "Periode menginap",
    duration: "Durasi",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guestsRooms: "Tamu / Kamar",
    paymentMethod: "Metode Bayar",
    total: "Total",
    roomSubtotal: "Subtotal kamar",
    breakfast: "Sarapan",
    subtotal: "Subtotal",
    appFee: "Biaya layanan aplikasi",
    tax: "Pajak",
    payNow: "Bayar Sekarang",
    reviewStatus: "Status review",
    reviewNeeded: "Belum direview",
    reviewCompleted: "Sudah direview",
    openReviewCenter: "Buka Pusat Review",
    yourReview: "Ulasan Anda",
    reviewSentAt: "Dikirim",
    tenantReply: "Balasan Tenant",
    tenantRepliedAt: "Dibalas pada",
    writeReview: "Tulis Ulasan",
    reviewPlaceholder: "Bagikan pengalaman menginap Anda...",
    submitReview: "Kirim Ulasan",
    submittingReview: "Mengirim...",
    searchStartDate: "Tanggal mulai",
    searchEndDate: "Tanggal akhir",
    searchOrderLabel: "Nomor pesanan",
    sortByLabel: "Urutkan berdasarkan",
    sortOrderLabel: "Arah urutan",
    sortByCreatedAt: "Tanggal dibuat",
    sortByCheckIn: "Tanggal check-in",
    sortByTotalAmount: "Total transaksi",
    sortByOrderNo: "Nomor pesanan",
    sortOrderAsc: "Menaik",
    sortOrderDesc: "Menurun",
    pageInfo: "Halaman",
    prevPage: "Sebelumnya",
    nextPage: "Berikutnya",
    ratingOptions: [
      { value: "5", label: "5 - Sangat baik" },
      { value: "4", label: "4 - Baik" },
      { value: "3", label: "3 - Cukup" },
      { value: "2", label: "2 - Kurang" },
      { value: "1", label: "1 - Buruk" },
    ],
  },
  en: {
    loginAgain: "Please sign in again.",
    failedLoad: "Failed to load transactions.",
    failedReview: "Failed to submit review.",
    reviewSuccess: "Review submitted successfully.",
    ratingRange: "Review rating must be between 1 and 5.",
    reviewRequired: "Review comment is required.",
    historyEyebrow: "Transaction History",
    historyTitle: "Your booking transactions",
    historySubtitle: "Search by order number or a transaction creation date range.",
    backHome: "Back to Home",
    myReviews: "My Reviews",
    refresh: "Refresh",
    refreshing: "Refreshing...",
    searchOrderPlaceholder: "Search order number",
    applySearch: "Search",
    resetSearch: "Reset",
    emptyState: "No transactions yet.",
    fallbackRoomName: "Room",
    bookedAt: "Booked",
    stayPeriod: "Stay period",
    duration: "Duration",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guestsRooms: "Guests / Rooms",
    paymentMethod: "Payment method",
    total: "Total",
    roomSubtotal: "Room subtotal",
    breakfast: "Breakfast",
    subtotal: "Subtotal",
    appFee: "Application service fee",
    tax: "Tax",
    payNow: "Pay Now",
    reviewStatus: "Review status",
    reviewNeeded: "Not reviewed yet",
    reviewCompleted: "Reviewed",
    openReviewCenter: "Open Review Center",
    yourReview: "Your Review",
    reviewSentAt: "Submitted",
    tenantReply: "Tenant Reply",
    tenantRepliedAt: "Replied at",
    writeReview: "Write a Review",
    reviewPlaceholder: "Share your stay experience...",
    submitReview: "Submit Review",
    submittingReview: "Submitting...",
    searchStartDate: "Start date",
    searchEndDate: "End date",
    searchOrderLabel: "Order number",
    sortByLabel: "Sort by",
    sortOrderLabel: "Sort direction",
    sortByCreatedAt: "Created date",
    sortByCheckIn: "Check-in date",
    sortByTotalAmount: "Transaction total",
    sortByOrderNo: "Order number",
    sortOrderAsc: "Ascending",
    sortOrderDesc: "Descending",
    pageInfo: "Page",
    prevPage: "Previous",
    nextPage: "Next",
    ratingOptions: [
      { value: "5", label: "5 - Excellent" },
      { value: "4", label: "4 - Good" },
      { value: "3", label: "3 - Fair" },
      { value: "2", label: "2 - Poor" },
      { value: "1", label: "1 - Bad" },
    ],
  },
};
