import type { PaymentCopyMap } from "./payment-types";

export const PAYMENT_COPY: PaymentCopyMap = {
  id: {
    payment: "Pembayaran",
    finishPayment: "Selesaikan pembayaran pesanan Anda",
    orderNo: "No. Pesanan",
    total: "Total",
    method: "Metode",
    paymentLimit: "Batas pembayaran",
    manualTransfer: "Transfer Manual",
    paymentGateway: "Gateway Pembayaran",
    roomSubtotal: "Subtotal kamar",
    breakfast: "Sarapan",
    subtotal: "Subtotal",
    appServiceFee: "Biaya layanan aplikasi (2%)",
    tax: "Pajak (11%)",
    paymentInstructions: "Instruksi pembayaran",
    uploadProofTitle: "Unggah Bukti Transfer",
    uploadProofHint: "Format: JPG/PNG, maksimal 1MB.",
    uploadProofButton: "Unggah Bukti Pembayaran",
    uploading: "Mengunggah...",
    continuePayment: "Lanjutkan Pembayaran",
    continuePaymentHint: "Setelah pembayaran sukses, status pesanan akan diproses otomatis.",
    toGateway: "Lanjutkan ke Gateway Pembayaran",
    redirecting: "Mengarahkan...",
    backToHome: "Back to Home",
    viewUploadedFile: "Lihat berkas yang diunggah",
    transferInstruction1: "Transfer sesuai total ke rekening yang ditentukan.",
    transferInstruction2: "Unggah bukti transfer di bawah ini.",
    transferInstruction3: "Pesanan akan diproses setelah pembayaran terverifikasi tenant.",
    gatewayInstruction1: "Klik tombol bayar untuk lanjut ke halaman gateway pembayaran.",
    gatewayInstruction2: "Pilih channel pembayaran yang tersedia.",
    gatewayInstruction3: "Status pesanan diperbarui otomatis saat pembayaran berhasil.",
    orderIdMissing: "ID pesanan tidak tersedia. Ulangi proses dari halaman konfirmasi pesanan.",
    fileLabel: "Berkas:",
    checkInOutArrow: "→",
    failedGatewayNoUrl:
      "URL invoice gateway pembayaran tidak tersedia. Silakan ulangi pesanan dari halaman sebelumnya.",
    gatewayOrderError:
      "Pesanan ini menggunakan gateway pembayaran. Lanjutkan pembayaran melalui gateway.",
    orderIdNotFound: "ID pesanan tidak ditemukan. Ulangi dari halaman konfirmasi.",
    chooseProofFirst: "Pilih file bukti transfer terlebih dahulu.",
    reloginUpload: "Silakan login kembali untuk mengunggah bukti transfer.",
    failedUpload: "Gagal mengunggah bukti pembayaran.",
    uploadSuccess: "Bukti pembayaran berhasil diunggah.",
    invalidProofType: "Format file harus JPG/PNG.",
    invalidProofSize: "Ukuran file maksimum 1MB.",
    confirmUploadTitle: "Konfirmasi upload bukti",
    confirmUploadDescription: "Pastikan bukti transfer yang diunggah sudah benar.",
    confirmUploadButton: "Ya, upload",
    confirmGatewayTitle: "Konfirmasi lanjut ke gateway",
    confirmGatewayDescription:
      "Anda akan diarahkan ke halaman pembayaran gateway untuk menyelesaikan transaksi.",
    confirmGatewayButton: "Lanjutkan",
    cancelAction: "Batal",
    cancelBookingButton: "Batalkan booking",
    cancelBookingFailed: "Gagal membatalkan booking. Silakan coba lagi.",
  },
  en: {
    payment: "Payment",
    finishPayment: "Complete your booking payment",
    orderNo: "Order No.",
    total: "Total",
    method: "Method",
    paymentLimit: "Payment deadline",
    manualTransfer: "Manual transfer",
    paymentGateway: "Payment gateway",
    roomSubtotal: "Room subtotal",
    breakfast: "Breakfast",
    subtotal: "Subtotal",
    appServiceFee: "App service fee (2%)",
    tax: "Tax (11%)",
    paymentInstructions: "Payment instructions",
    uploadProofTitle: "Upload transfer proof",
    uploadProofHint: "Format: JPG/PNG, max 1MB.",
    uploadProofButton: "Upload payment proof",
    uploading: "Uploading...",
    continuePayment: "Continue payment",
    continuePaymentHint: "After successful payment, booking status updates automatically.",
    toGateway: "Continue to payment gateway",
    redirecting: "Redirecting...",
    backToHome: "Back to Home",
    viewUploadedFile: "View uploaded file",
    transferInstruction1: "Transfer the exact total to the designated account.",
    transferInstruction2: "Upload payment proof below.",
    transferInstruction3: "Booking is processed after tenant verifies payment.",
    gatewayInstruction1: "Click pay to continue to the payment gateway page.",
    gatewayInstruction2: "Choose an available payment channel.",
    gatewayInstruction3: "Booking status updates automatically after success.",
    orderIdMissing: "Order ID is unavailable. Repeat from booking confirmation page.",
    fileLabel: "File:",
    checkInOutArrow: "→",
    failedGatewayNoUrl:
      "Payment gateway invoice URL is unavailable. Please repeat booking from previous page.",
    gatewayOrderError:
      "This booking uses payment gateway. Please continue through the gateway.",
    orderIdNotFound: "Order ID not found. Please repeat from confirmation page.",
    chooseProofFirst: "Please choose transfer proof file first.",
    reloginUpload: "Please sign in again to upload transfer proof.",
    failedUpload: "Failed to upload payment proof.",
    uploadSuccess: "Payment proof uploaded successfully.",
    invalidProofType: "File format must be JPG/PNG.",
    invalidProofSize: "Maximum file size is 1MB.",
    confirmUploadTitle: "Confirm proof upload",
    confirmUploadDescription: "Make sure the transfer proof is correct before upload.",
    confirmUploadButton: "Yes, upload",
    confirmGatewayTitle: "Confirm continue to gateway",
    confirmGatewayDescription:
      "You will be redirected to the payment gateway page to complete this transaction.",
    confirmGatewayButton: "Continue",
    cancelAction: "Cancel",
    cancelBookingButton: "Cancel booking",
    cancelBookingFailed: "Failed to cancel booking. Please try again.",
  },
};
