import type { AppLocale } from "@/lib/app-locale";

export type PaymentMethod = "MANUAL_TRANSFER" | "XENDIT";

export type PaymentCopy = {
  payment: string;
  finishPayment: string;
  orderNo: string;
  total: string;
  method: string;
  paymentLimit: string;
  manualTransfer: string;
  paymentGateway: string;
  roomSubtotal: string;
  breakfast: string;
  subtotal: string;
  appServiceFee: string;
  tax: string;
  paymentInstructions: string;
  uploadProofTitle: string;
  uploadProofHint: string;
  uploadProofButton: string;
  uploading: string;
  continuePayment: string;
  continuePaymentHint: string;
  toGateway: string;
  redirecting: string;
  backToHome: string;
  viewUploadedFile: string;
  transferInstruction1: string;
  transferInstruction2: string;
  transferInstruction3: string;
  gatewayInstruction1: string;
  gatewayInstruction2: string;
  gatewayInstruction3: string;
  orderIdMissing: string;
  fileLabel: string;
  checkInOutArrow: string;
  failedGatewayNoUrl: string;
  gatewayOrderError: string;
  orderIdNotFound: string;
  chooseProofFirst: string;
  reloginUpload: string;
  failedUpload: string;
  uploadSuccess: string;
  invalidProofType: string;
  invalidProofSize: string;
  confirmUploadTitle: string;
  confirmUploadDescription: string;
  confirmUploadButton: string;
  confirmGatewayTitle: string;
  confirmGatewayDescription: string;
  confirmGatewayButton: string;
  cancelAction: string;
  cancelBookingButton: string;
  cancelBookingFailed: string;
};

export type PaymentCopyMap = Record<AppLocale, PaymentCopy>;

export type PaymentQueryData = {
  bookingId: string;
  orderNo: string;
  total: string;
  paymentDueAt: string;
  propertyName: string;
  roomName: string;
  checkIn: string;
  checkOut: string;
  paymentMethod: PaymentMethod;
  xenditInvoiceUrl: string;
  subtotalAmount: string;
  roomSubtotal: string;
  breakfastSelected: boolean;
  breakfastPax: string;
  breakfastUnitPrice: string;
  breakfastTotal: string;
  appFeeAmount: string;
  taxAmount: string;
};
