export const SEARCH_COPY_EN = {
  allDestinations: "All destinations",
  headerChoicePrefix: "Options in",
  headerDefaultTitle: "Choose the right property",
  flexibleDates: "Flexible dates",
  flexibleGuests: "Flexible guests",
  backToHome: "Back to Home",
  searchResults: "Search results",
  filter: "Filter",
  adjustSearch: "Adjust search",
  location: "Location",
  destination: "Destination",
  destinationPlaceholder: "Type destination city",
  propertyName: "Property name",
  optional: "Optional",
  category: "Category",
  allCategories: "All categories",
  amenities: "Amenities",
  amenitiesHint: "Choose the amenities you need.",
  filterMode: "Filter mode",
  filterAny: "Any selected",
  filterAll: "All selected",
  hide: "Hide",
  otherAmenities: "More amenities",
  stay: "Stay",
  travelDate: "Departure date",
  stayDuration: "Stay duration",
  decreaseStayAria: "Decrease stay duration",
  increaseStayAria: "Increase stay duration",
  adults: "Adults",
  children: "Children",
  totalRooms: "Rooms",
  decreaseAdultsAria: "Decrease adults",
  increaseAdultsAria: "Increase adults",
  decreaseChildrenAria: "Decrease children",
  increaseChildrenAria: "Increase children",
  decreaseRoomsAria: "Decrease rooms",
  increaseRoomsAria: "Increase rooms",
  applySearch: "Apply search",
  filterSummary: "Filter summary",
  editFilters: "Edit filters",
  hideFilters: "Hide filters",
  advancedFilters: "Advanced filters",
  hideAdvancedFilters: "Hide advanced",
  loadingResults: "Loading search results...",
  showingPrefix: "Showing",
  showingSuffix: "properties",
  locationConnector: "in",
  loadingListings: "Loading...",
  listingChoicesSuffix: "options for you",
  sortBy: "Sort by",
  sortName: "Name",
  sortPrice: "Price",
  sortAsc: "Ascending",
  sortDesc: "Descending",
  rating: "Rating",
  breakfastAvailable: "Breakfast available",
  noBreakfast: "No breakfast option",
  priceUnavailable: "Price not available",
  perNight: "/ night",
  totalLabel: "Total",
  notIncludeFees: "Excludes 2% app service fee and 11% tax.",
  viewDetails: "View details",
  noResults: "No properties match your search yet.",
  previous: "Previous",
  next: "Next",
  guestSingular: "guest",
  guestPlural: "guests",
  nightSingular: "night",
  nightPlural: "nights",
  roomSingular: "room",
  roomPlural: "rooms",
  peopleUnit: "people",
  amenityPrefix: "Amenities",
  propertyTagFallback: "Property",
  highlightAddress: "Easy access and strategic location",
  highlightDefault: "Verified property",
  failedLoadResults: "Failed to load search results.",
} as const;
