export const SEARCH_COPY_ID = {
  allDestinations: "Semua destinasi",
  headerChoicePrefix: "Pilihan di",
  headerDefaultTitle: "Pilih properti yang cocok",
  flexibleDates: "Tanggal fleksibel",
  flexibleGuests: "Tamu fleksibel",
  backToHome: "Kembali ke Home",
  searchResults: "Hasil pencarian",
  filter: "Filter",
  adjustSearch: "Atur pencarian",
  location: "Lokasi",
  destination: "Destinasi",
  destinationPlaceholder: "Ketik kota tujuan",
  propertyName: "Nama properti",
  optional: "Opsional",
  category: "Kategori",
  allCategories: "Semua kategori",
  amenities: "Fasilitas",
  amenitiesHint: "Pilih fasilitas yang dibutuhkan.",
  filterMode: "Mode filter",
  filterAny: "Salah satu",
  filterAll: "Semua terpilih",
  hide: "Sembunyikan",
  otherAmenities: "Fasilitas lain",
  stay: "Menginap",
  travelDate: "Tanggal berangkat",
  stayDuration: "Durasi menginap",
  decreaseStayAria: "Kurangi durasi menginap",
  increaseStayAria: "Tambah durasi menginap",
  adults: "Dewasa",
  children: "Anak",
  totalRooms: "Jumlah kamar",
  decreaseAdultsAria: "Kurangi jumlah dewasa",
  increaseAdultsAria: "Tambah jumlah dewasa",
  decreaseChildrenAria: "Kurangi jumlah anak",
  increaseChildrenAria: "Tambah jumlah anak",
  decreaseRoomsAria: "Kurangi jumlah kamar",
  increaseRoomsAria: "Tambah jumlah kamar",
  applySearch: "Terapkan pencarian",
  filterSummary: "Ringkasan filter",
  editFilters: "Ubah filter",
  hideFilters: "Sembunyikan filter",
  advancedFilters: "Filter lanjutan",
  hideAdvancedFilters: "Sembunyikan lanjutan",
  loadingResults: "Memuat hasil pencarian...",
  showingPrefix: "Menampilkan",
  showingSuffix: "properti",
  locationConnector: "di",
  loadingListings: "Memuat...",
  listingChoicesSuffix: "pilihan untuk Anda",
  sortBy: "Urutkan",
  sortName: "Nama",
  sortPrice: "Harga",
  sortAsc: "Ascending",
  sortDesc: "Descending",
  rating: "Rating",
  breakfastAvailable: "Sarapan tersedia",
  noBreakfast: "Tanpa opsi sarapan",
  priceUnavailable: "Harga belum tersedia",
  perNight: "/ malam",
  totalLabel: "Total",
  notIncludeFees: "Belum termasuk biaya layanan aplikasi 2% dan pajak 11%.",
  viewDetails: "Lihat detail",
  noResults: "Belum ada properti yang sesuai dengan pencarianmu.",
  previous: "Sebelumnya",
  next: "Selanjutnya",
  guestSingular: "tamu",
  guestPlural: "tamu",
  nightSingular: "malam",
  nightPlural: "malam",
  roomSingular: "kamar",
  roomPlural: "kamar",
  peopleUnit: "orang",
  amenityPrefix: "Fasilitas",
  propertyTagFallback: "Properti",
  highlightAddress: "Akses mudah dan lokasi strategis",
  highlightDefault: "Properti terverifikasi",
  failedLoadResults: "Gagal memuat hasil pencarian.",
} as const;
