export const HOME_COPY_ID = {
  languageLabel: "Bahasa",
  navTenantHome: "Beranda",
  navTenantProperty: "Sewakan Properti",
  navStay: "Tempat Menginap",
  navExplore: "Jelajah",
  navSupport: "Bantuan",
  searchHeaderCta: "Cari Penginapan",
  menuOpenAria: "Buka menu",
  menuCloseAria: "Tutup menu",
  greeting: "Halo",
  menuLabel: "Menu",
  tenantDashboard: "Dashboard Tenant",
  myProfile: "Profil Saya",
  myTransactions: "Transaksi Saya",
  myReviews: "Review Saya",
  logout: "Keluar",
  login: "Masuk",
  defaultHeroTitle: "Temukan Properti Aktif di BookIn",
  defaultHeroLoadingSubtitle: "Sedang memuat listing terbaru...",
  defaultHeroEmptySubtitle: "Belum ada properti aktif untuk ditampilkan.",
  defaultHeroDescription: "Gunakan form pencarian untuk melihat ketersediaan properti secara realtime.",
  defaultHeroPricePrefix: "Harga mulai",
  defaultHeroPriceSuffix: "per malam.",
  defaultHeroNoPrice: "Lihat detail properti dan cek ketersediaan kamar.",
  searchFormLabel: "Form Pencarian",
  searchFormTitle: "Tentukan destinasi dan waktu menginap Anda",
  searchWhereLabel: "Lokasi",
  searchWherePlaceholder: "Cari kota tujuan",
  searchWhenLabel: "Tanggal",
  searchWhoLabel: "Tamu",
  searchSubmitAria: "Cari properti",
  searchSubmitText: "Cari",
  searchDateEmpty: "Tambah tanggal",
  whenPanelTitle: "Pilih tanggal",
  checkInLabel: "Check-in",
  stayDuration: "Durasi menginap",
  whoPanelTitle: "Jumlah tamu",
  adultsLabel: "Dewasa",
  adultsHint: "Usia 13 tahun ke atas",
  childrenLabel: "Anak",
  childrenHint: "Usia 0 - 12 tahun",
  nightSingular: "malam",
  nightPlural: "malam",
  guestSingular: "tamu",
  guestPlural: "tamu",
  discoverTitle: "Jelajahi kategori populer",
  seeListings: "Lihat listing",
  allCategories: "Semua",
  propertiesLabel: "Properti Tersedia",
  propertiesTitle: "Temukan properti yang siap dipesan",
  checkAvailability: "Cek ketersediaan",
  loadingListings: "Memuat listing properti terbaru...",
  noPropertiesMatched: "Belum ada properti yang cocok dengan filter saat ini.",
  amenitiesPrefix: "Fasilitas",
  roomDetailsFallback: "Cek detail kamar",
  roomAvailabilityFallback: "Lihat detail ketersediaan kamar",
  perNight: "/ malam",
  propertyPriceFallback: "Harga tersedia di detail properti",
  viewDetails: "Lihat detail",
  destinationNoExactPrefix: "Belum ada properti di",
  destinationNoExactSuffix: "Coba destinasi lain yang terdekat.",
  destinationNearbyPrefix: "Belum ada properti tepat di",
  destinationNearbySuffix: "Kami tampilkan opsi terdekat dalam radius 1 km.",
  destinationNearbyEmptySuffix: "dan area sekitarnya dalam radius 1 km.",
  failedLoadProperties: "Gagal memuat properti.",
  statsAvailableDesc: "Data listing realtime dari backend.",
  statsCategories: "Kategori Aktif",
  statsCategoriesDesc: "Diambil langsung dari kategori properti.",
  statsCities: "Kota Destinasi",
  statsCitiesDesc: "Kota dengan properti yang siap dipesan.",
  tenantModeLabel: "Hosting Mode",
  tenantHeroTitle: "Sewakan properti Anda dengan tampilan host yang lebih modern",
  tenantHeroDesc: "Dashboard tenant tetap dipertahankan, sementara home sekarang lebih eksploratif agar konsisten dengan pengalaman tamu.",
  tenantPrimaryCta: "Isi Detail Properti",
  footerAboutTitle: "Tentang BookIn",
  footerAboutDesc: "Platform booking akomodasi dengan pencarian cepat, visual listing jelas, dan alur reservasi transparan.",
  footerFeaturesTitle: "Fitur Utama",
  footerFeature1: "Pencarian destinasi + filter fleksibel",
  footerFeature2: "Foto listing besar dan informatif",
  footerFeature3: "Ringkasan harga per malam",
  footerContactTitle: "Kontak",
  footerContactHours: "Jam layanan: 08.00 - 22.00 WIB",
  footerNavigationTitle: "Navigasi",
  footerNavHome: "Beranda",
  footerNavSearch: "Pencarian",
  footerNavProperties: "Properti",
  authRequired: "Silakan login terlebih dahulu untuk mengakses halaman tersebut.",
  authUnverified: "Akun Anda belum terverifikasi. Silakan verifikasi email terlebih dahulu.",
  authForbidden: "Anda tidak memiliki akses ke halaman tersebut.",
  slidePrevAria: "Slide sebelumnya",
  slideNextAria: "Slide selanjutnya",
} as const;
