export const HOME_COPY_EN = {
  languageLabel: "Language",
  navTenantHome: "Home",
  navTenantProperty: "List Property",
  navStay: "Stays",
  navExplore: "Explore",
  navSupport: "Support",
  searchHeaderCta: "Find Stays",
  menuOpenAria: "Open menu",
  menuCloseAria: "Close menu",
  greeting: "Hi",
  menuLabel: "Menu",
  tenantDashboard: "Tenant Dashboard",
  myProfile: "My Profile",
  myTransactions: "My Transactions",
  myReviews: "My Reviews",
  logout: "Log out",
  login: "Sign in",
  defaultHeroTitle: "Discover Active Properties on BookIn",
  defaultHeroLoadingSubtitle: "Loading the latest listings...",
  defaultHeroEmptySubtitle: "No active properties are available yet.",
  defaultHeroDescription: "Use the search form to check real-time property availability.",
  defaultHeroPricePrefix: "Starting from",
  defaultHeroPriceSuffix: "per night.",
  defaultHeroNoPrice: "View property details and room availability.",
  searchFormLabel: "Search Form",
  searchFormTitle: "Set your destination and stay dates",
  searchWhereLabel: "Where",
  searchWherePlaceholder: "Search destination city",
  searchWhenLabel: "When",
  searchWhoLabel: "Who",
  searchSubmitAria: "Search properties",
  searchSubmitText: "Go",
  searchDateEmpty: "Add dates",
  whenPanelTitle: "Select dates",
  checkInLabel: "Check-in",
  stayDuration: "Stay duration",
  whoPanelTitle: "Guest count",
  adultsLabel: "Adults",
  adultsHint: "Ages 13 and above",
  childrenLabel: "Children",
  childrenHint: "Ages 0 - 12",
  nightSingular: "night",
  nightPlural: "nights",
  guestSingular: "guest",
  guestPlural: "guests",
  discoverTitle: "Explore popular categories",
  seeListings: "View listings",
  allCategories: "All",
  propertiesLabel: "Available Properties",
  propertiesTitle: "Find properties ready to book",
  checkAvailability: "Check availability",
  loadingListings: "Loading the latest property listings...",
  noPropertiesMatched: "No properties match your current filters yet.",
  amenitiesPrefix: "Amenities",
  roomDetailsFallback: "Check room details",
  roomAvailabilityFallback: "View room availability details",
  perNight: "/ night",
  propertyPriceFallback: "Price is available on the property detail page",
  viewDetails: "View details",
  destinationNoExactPrefix: "No properties found in",
  destinationNoExactSuffix: "Try another nearby destination.",
  destinationNearbyPrefix: "No exact properties found in",
  destinationNearbySuffix: "Showing nearby options within a 1 km radius.",
  destinationNearbyEmptySuffix: "and surrounding areas within a 1 km radius.",
  failedLoadProperties: "Failed to load properties.",
  statsAvailableDesc: "Real-time listing data from backend.",
  statsCategories: "Active Categories",
  statsCategoriesDesc: "Fetched directly from property categories.",
  statsCities: "Destination Cities",
  statsCitiesDesc: "Cities with properties ready to book.",
  tenantModeLabel: "Hosting Mode",
  tenantHeroTitle: "List your property with a cleaner host experience",
  tenantHeroDesc: "The tenant dashboard stays familiar, while home now feels more exploratory for better guest consistency.",
  tenantPrimaryCta: "Complete Property Details",
  footerAboutTitle: "About BookIn",
  footerAboutDesc: "An accommodation booking platform with faster search, clearer listing visuals, and transparent reservation flow.",
  footerFeaturesTitle: "Key Features",
  footerFeature1: "Destination search with flexible filters",
  footerFeature2: "Large and informative listing photos",
  footerFeature3: "Per-night price summary",
  footerContactTitle: "Contact",
  footerContactHours: "Service hours: 08:00 - 22:00 WIB",
  footerNavigationTitle: "Navigation",
  footerNavHome: "Home",
  footerNavSearch: "Search",
  footerNavProperties: "Properties",
  authRequired: "Please sign in first to access that page.",
  authUnverified: "Your account is not verified yet. Please verify your email first.",
  authForbidden: "You do not have access to that page.",
  slidePrevAria: "Previous slide",
  slideNextAria: "Next slide",
} as const;
