import type { AppLocale } from "@/lib/app-locale";

export const BOOKING_COPY = {
  id: {
    failedLoadBooking: "Gagal memuat pesanan.",
    failedLoadProperty: "Gagal memuat daftar properti.",
    incompleteForm: "Lengkapi data pemesanan terlebih dahulu.",
    previewFailed: "Pratinjau gagal.",
    createFailed: "Terjadi kesalahan saat membuat pemesanan.",
    createdSuccess: "Pemesanan berhasil dibuat.",
    createFailedFallback: "Gagal membuat pemesanan",
    pageTitle: "Pemesanan",
    createTitle: "Buat Pemesanan",
    property: "Properti",
    selectProperty: "Pilih properti",
    loadingPropertyList: "Memuat daftar properti...",
    roomType: "Tipe Kamar",
    selectRoom: "Pilih kamar",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guests: "Tamu",
    rooms: "Kamar",
    previewPrice: "Pratinjau Harga",
    previewing: "Meninjau...",
    creating: "Membuat...",
    createBooking: "Buat Pemesanan",
    previewTitle: "Pratinjau Harga",
    total: "Total",
    totalNights: "Jumlah malam",
    basePrice: "Harga dasar",
    adjustment: "Penyesuaian",
    finalPrice: "Harga akhir",
    stock: "Stok tersedia",
    listTitle: "Daftar Pesanan Saya",
    refreshStatus: "Muat Ulang Status",
    refreshing: "Memuat ulang...",
    noOrders: "Belum ada pesanan.",
    orderNo: "No. Pesanan",
    date: "Tanggal",
    status: "Status",
  },
  en: {
    failedLoadBooking: "Failed to load bookings.",
    failedLoadProperty: "Failed to load properties.",
    incompleteForm: "Please complete booking details first.",
    previewFailed: "Preview failed.",
    createFailed: "Something went wrong while creating booking.",
    createdSuccess: "Booking created successfully.",
    createFailedFallback: "Failed to create booking",
    pageTitle: "Booking",
    createTitle: "Create Booking",
    property: "Property",
    selectProperty: "Select property",
    loadingPropertyList: "Loading properties...",
    roomType: "Room Type",
    selectRoom: "Select room",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guests: "Guests",
    rooms: "Rooms",
    previewPrice: "Price Preview",
    previewing: "Previewing...",
    creating: "Creating...",
    createBooking: "Create Booking",
    previewTitle: "Price Preview",
    total: "Total",
    totalNights: "Total nights",
    basePrice: "Base price",
    adjustment: "Adjustment",
    finalPrice: "Final price",
    stock: "Available stock",
    listTitle: "My Booking List",
    refreshStatus: "Refresh Status",
    refreshing: "Refreshing...",
    noOrders: "No bookings yet.",
    orderNo: "Order No.",
    date: "Date",
    status: "Status",
  },
} satisfies Record<AppLocale, Record<string, string>>;
